Add functionality to detect spam bot join waves
Yuhanun/Better-C-Bot pull request #23
Opened 2021-04-26 21:25 UTC by The-personified-devil

The exception handling/response for running a command with the has_role check whilst missing role is not yet implemented.

2021-04-27 21:50 UTC, The-personified-devil commented
Borrowed the code for the exception handling from https://gist.github.com/EvieePy/7822af90858ef65012ea500bcecf1612.

2021-04-28 01:05 UTC, The-personified-devil commented
Made it back into a draft, because Lenny showed me a *lot* of issues, that still need to be fixed.

2021-04-28 09:47 UTC, Yuhanun requested changes

2021-04-28 09:47 UTC, Yuhanun commented on src/cogs/error_handler.py
> +                return
if cog and cog._get_...

2021-04-28 09:47 UTC, Yuhanun commented on src/cogs/rules.py
> +        return dm_channel
```suggestion
        return member.dm_channel or await member.create_dm()
```

You don't have to create a dm channel tho, discord.py internally already does this 🤷

2021-04-28 09:47 UTC, Yuhanun commented on src/cogs/rules.py
> +        selected_staff = [
or just ping the staff role?...

2021-05-04 18:22 UTC, Mehodin approved these changes

2021-05-04 18:23 UTC, merged