Upgrades for snipe
Yuhanun/Better-C-Bot pull request #58
Opened 2023-01-08 19:31 UTC by The-personified-devil

fix: Fix the large message chunker creating empty chunks, causing errors

2023-01-09 18:19 UTC, Yuhanun approved these changes

2023-01-25 17:49 UTC, Tsche requested changes
See review comments. Also please remove the `draft` tag

2023-01-25 17:49 UTC, Tsche commented on src/util/util.py
> +        if len(msg) > 0 and not msg.isspace():
non-empty strings are truthy, do not explicitly check for string length > 0

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        buffer = buffer[-conf.max_del_msgs:]
use circular buffer or deque with maxlen instead

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        c_id = message.channel.id
`c_id` should be `channel_id`, be more verbose

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +            self._deleted[c_id] = []
use `collections.defaultdict` for `self._deleted`, default to `deque(maxlen=conf.max_del_msgs)`

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +            self._message_history[old.id] = []
use `collections.defaultdict`

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        }
I do not like this approach, this is rather costly in a handler that gets called frequently

2023-01-25 17:49 UTC, Tsche commented on src/util/snipe.py
> +    avatar = history[0].author.display_avatar
OOB if history is empty

2023-01-25 17:49 UTC, Tsche commented on src/util/snipe.py
> +        embed = discord.Embed(description=state.content, timestamp=timestamp(state)).set_author(name=author, icon_url=avatar)
.display_avatar is optional, hence avatar might be `None`. what happens if the author has no avatar?

2023-01-25 17:49 UTC, Tsche commented on src/util/snipe.py
> +    for (length, embed) in embeds:
extraneous braces

2023-01-25 17:49 UTC, Tsche commented on src/util/util.py
> +
grouping: why separate these lines by an empty line?

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        self._message_history: dict[int, list[discord.Message]] = {}
misleading: `self._message_history` is not of type `MessageHistory`

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        index = abs(number)
extraneous, command invocation will fail for floats anyway. Since it's annotated it will be validated.

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        histories = self._deleted[ctx.channel.id]
misleading: This is one history of messages, not multiple histories. Did you mean `messages`?

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        history = histories[-1 - index]
readability: reverse `histories` prior to this or build `histories` in reverse order to begin with

2023-01-25 17:49 UTC, Tsche commented on src/cogs/snipe.py
> +        self._deleted[ctx.channel.id] = []
redundant: prefer `del self._deleted[ctx.channel.id]`. Insertion of the new default value happens in the message deletion handler anyway

2023-01-28 02:50 UTC, Tsche approved these changes

2023-01-29 22:20 UTC, Yuhanun approved these changes

2023-01-29 22:20 UTC, merged